source:
  - name: custom_nodes
    type: file
    url: https://raw.githubusercontent.com/qjlxg/aggregator/refs/heads/main/ss.txt
proxy:
  - type: ss
  - type: ssr
  - type: vmess
  - type: vless
  - type: trojan
  - type: hysteria2
check:
  interval: 3600
  timeout: 20
  concurrency: 2
  speedtest: true
  speedtest_url: https://speed.cloudflare.com/__down?bytes=5000000
  debug: true
output:
  path: /output/NodeDownloadSpeedTest.yaml
  format: yaml
