name: Process Proxy Links

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches:
      - main # 或者你的默认分支名称，例如 master
    paths:
      - 'process_links.py' # 当 process_links.py 变化时触发
      - '.github/workflows/process_nodes.yml' # 当工作流文件自身变化时触发
      - 'sc/**' # 可选：当 sc 目录下的文件变化时触发 (如果你希望在生成文件后，再次有文件变化也触发)
      - 'urls.txt' # 如果你把URL列表放在单独的文件中，也将其包含进来
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次，可以根据需要调整

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # 推荐使用Python 3.9或更高版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml

    - name: Run script to process links
      run: python process_links.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add sc/ # 添加sc目录下的所有文件
        git commit -m "Update proxy nodes" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
