name: Test Node Download Speed

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 授予写权限

jobs:
  test-node-speed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run proxypool with progress logging
        run: |
          mkdir -p sc
          rm -f sc/* || true  # 清理旧文件
          docker run -d --name proxypool \
            -v $(pwd)/config:/config \
            -v $(pwd)/sc:/output \
            asdlokj1qpi23/proxypool \
            -c /config/config.yaml
          # 实时输出日志，模拟进度条
          docker logs -f proxypool &
          # 等待容器完成
          until [ "$(docker inspect -f '{{.State.Status}}' proxypool)" != "running" ]; do
            echo "Testing in progress... $(date)"
            sleep 10
          done
          EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' proxypool)
          echo "Container exited with code: $EXIT_CODE"
          docker stop proxypool || true
          docker rm proxypool || true

      - name: Check output file
        run: |
          ls -l sc/ || echo "No files in sc directory"
          cat sc/NodeDownloadSpeedTest.yaml || echo "Output file not found"

      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add sc/NodeDownloadSpeedTest.yaml
          git commit -m "Update node speed test results" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
