
# 工作流名称
name: Node Parser Workflow

# 触发条件
on:
  push:
    branches:
      - main  # 当推送代码到 main 分支时触发
  pull_request:
    branches:
      - main  # 当提交 PR 到 main 分支时触发

# 工作流任务
jobs:
  parse-nodes:
    # 指定运行环境
    runs-on: ubuntu-latest

    # 任务步骤
    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 使用 Python 3.10
          cache: 'pip'  # 缓存 pip 依赖以加速构建

      # 安装依赖
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests PyYAML pysocks

      # 运行 node_parser.py 脚本
      - name: 运行节点解析脚本
        run: |
          python node_parser.py > node_parser_output.txt
        continue-on-error: true  # 如果脚本运行失败，继续执行后续步骤

      # 上传解析结果作为工件
      - name: 上传解析结果
        uses: actions/upload-artifact@v4
        with:
          name: node-parser-results
          path: node_parser_output.txt
          retention-days: 7  # 保留 7 天

      # 检查解析结果（可选）
      - name: 检查解析结果
        run: |
          if [ -s node_parser_output.txt ]; then
            echo "节点解析成功，输出文件不为空"
            cat node_parser_output.txt
          else
            echo "节点解析失败或输出为空"
            exit 1
          fi
