name: Test Node Download Speed # 工作流名称

on:
  push:
    branches:
      - main # 当有新的提交推送到 main 分支时触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 00:00 运行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write # 授予写入权限，用于推送结果文件

jobs:
  test-node-speed:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu runner，默认是 x86_64 (AMD64) 架构

    steps:
      - name: Checkout repository # 检出你的代码，包括 node_parser.py 和 speed_tester.py
        uses: actions/checkout@v4

      - name: Set up Python # 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 推荐使用 3.10 或更高版本

      - name: Install Python dependencies # 安装 Python 依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests pysocks pyyaml

      # --- 下载并安装 Xray ---
      # 这个步骤会根据运行环境的架构自动选择下载正确的 Xray-core 文件
      - name: Download and Install Xray
        id: download_xray # 添加 ID 以便后续判断是否成功
        run: |
          XRAY_VERSION="25.7.25" # **已更新为 Xray-core v25.7.25**
          ARCH=$(uname -m)
          XRAY_FILE="" # 初始化文件名变量

          # 根据不同的架构选择对应的 Xray 文件名
          if [ "$ARCH" = "x86_64" ]; then
            # 对于 x86_64 (AMD64) 架构，这是 ubuntu-latest 默认使用的
            XRAY_FILE="Xray-linux-64.zip" # **已修正为 v25.7.25 实际的文件名**
          elif [ "$ARCH" = "aarch64" ]; then
            # 对于 ARM64 架构 (例如自托管的 ARM 机器)
            XRAY_FILE="Xray-linux-arm64-v8a.zip"
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi
          
          XRAY_URL="https://github.com/XTLS/Xray-core/releases/download/v${XRAY_VERSION}/${XRAY_FILE}"
          echo "Downloading Xray from: ${XRAY_URL}"
          
          # 使用 curl 下载并检查状态，增加重试机制和错误报告
          curl -fSsL --retry 5 --retry-delay 10 -o xray.zip "${XRAY_URL}"
          
          # 检查下载是否成功（文件是否存在且非空）
          if [ ! -s xray.zip ]; then
            echo "Xray download failed: xray.zip is empty or non-existent."
            exit 1
          fi
          
          # 解压 Xray 可执行文件到当前目录，并覆盖同名文件
          # 确保解压出来的可执行文件名为 'xray'
          if ! unzip -o xray.zip "xray" -d .; then
            echo "Failed to unzip xray.zip. It might be corrupted or not a valid zip file."
            exit 1
          fi
          
          chmod +x ./xray # 添加执行权限
          echo "Xray installed successfully."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub Token 提高下载稳定性

      # --- 下载并安装 Hysteria2 ---
      # **这里是主要修改的地方：更新 HY2_VERSION 和 URL 路径**
      - name: Download and Install Hysteria2
        id: download_hysteria2
        run: |
          HY2_VERSION="2.6.2" # **已更新为 Hysteria2 最新版本 app/v2.6.2**
          MACHINE_ARCH=$(uname -m)
          if [ "$MACHINE_ARCH" = "x86_64" ]; then
            HY2_FILE="hysteria-linux-amd64"
          elif [ "$MACHINE_ARCH" = "aarch64" ]; then
            HY2_FILE="hysteria-linux-arm64"
          else
            echo "Unsupported architecture: $MACHINE_ARCH"
            exit 1
          fi

          # **注意这里的 URL 路径变化，版本号前增加了 'app/'**
          HY2_URL="https://github.com/apernet/hysteria/releases/download/app/v${HY2_VERSION}/${HY2_FILE}"
          echo "Downloading Hysteria2 from: ${HY2_URL}"
          
          curl -fSsL --retry 5 --retry-delay 10 -o hysteria2 "${HY2_URL}"
          
          if [ ! -s hysteria2 ]; then
            echo "Hysteria2 download failed: hysteria2 is empty or non-existent."
            exit 1
          fi

          chmod +x ./hysteria2 # 添加执行权限
          echo "Hysteria2 installed successfully."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Node Speed Test Script # 运行你的 Python 脚本
        # **这里修改为运行 speed_tester.py**
        run: python speed_tester.py

      - name: Check output files # 检查生成的文件，以便调试
        run: |
          echo "Listing files in sc/ directory:"
          ls -l sc/ || echo "No files in sc directory"
          echo "--- Content of output TXT file ---"
          cat sc/${{ env.PROJECT_NAME }}_results.txt || echo "Output TXT file not found" # **文件名已更新**
          echo "--- Content of output YAML file ---"
          cat sc/${{ env.PROJECT_NAME }}_results.yaml || echo "Output YAML file not found" # **文件名已更新**
        env:
          PROJECT_NAME: NodeDownloadSpeedTest # 和 Python 脚本中的 PROJECT_NAME 保持一致

      - name: Commit and push results # 提交并推送结果文件到仓库
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add sc/* # 添加 sc 目录下的所有文件
          git commit -m "Update node speed test results" || echo "No changes to commit" # 如果没有文件更改，则不执行 commit
          git push origin main # 推送到 main 分支
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
