# 工作流名称
name: 订阅检查与节点更新 (Subconverter Direct)

# 触发工作流的事件
on:
  workflow_dispatch: # 允许手动从 GitHub Actions 页面触发此工作流
  schedule:
    - cron: '0 */6 * * *' # 每 6 小时运行一次 (例如，每天的 0点、6点、12点、18点)

jobs:
  update-clash-config:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 环境上运行

    steps:
      - name: 检出仓库 # 第一步：将你的 GitHub 仓库代码克隆到 Actions 运行环境中
        uses: actions/checkout@v4 # 使用 actions/checkout@v4 动作来完成此操作

      - name: 下载并解压 subconverter 二进制文件
        run: |
          # subconverter 最新 release 的下载地址 (Linux AMD64)
          # 注意：请定期检查 https://github.com/tindyguo/subconverter/releases 获取最新版本和正确的下载链接
          # 这里我们直接下载 subconverter-linux64.tar.gz
          SUB_CONVERTER_URL="https://github.com/tindyguo/subconverter/releases/latest/download/subconverter-linux64.tar.gz"
          
          echo "下载 subconverter 二进制文件..."
          curl -L "${SUB_CONVERTER_URL}" -o subconverter-linux64.tar.gz
          
          echo "解压 subconverter..."
          tar -xzvf subconverter-linux64.tar.gz
          
          # 确保解压后的二进制文件可执行
          chmod +x subconverter

          echo "subconverter 已准备就绪。"

      - name: 使用 subconverter 处理订阅并生成 Clash 配置
        shell: bash # 强制使用 Bash shell 来执行此步骤的脚本
        run: |
          # 定义你的订阅链接。subconverter 可以同时处理多个，用 | 分隔
          SUBSCRIPTION_URL_META="https://raw.githubusercontent.com/qjlxg/ss/refs/heads/master/list.meta.yml"
          SUBSCRIPTION_URL_SS_TXT="https://raw.githubusercontent.com/qjlxg/aggregator/refs/heads/main/ss.txt"
          
          # 定义输出文件存放的目录和最终的文件名
          OUTPUT_DIR="sc"
          OUTPUT_FILENAME="clash_config.yaml" # 新的文件名，避免与旧的混淆
          OUTPUT_PATH="${OUTPUT_DIR}/${OUTPUT_FILENAME}"

          echo "创建输出目录 ${OUTPUT_DIR}..."
          mkdir -p "$OUTPUT_DIR" # 如果 'sc/' 目录不存在，则创建它

          echo "使用 subconverter 处理订阅并生成 Clash 配置..."
          
          # **核心改动**：直接运行下载的 subconverter 二进制文件
          # subconverter 支持多种启动模式，这里我们启动其 Web API 模式，然后用 curl 访问
          # 注意：直接运行的 subconverter 会监听 localhost:25500
          
          # 启动 subconverter 作为后台服务
          # ./subconverter: 执行当前目录下的 subconverter 二进制文件
          # & 后台运行
          # 2>&1 > /dev/null &：将标准错误和标准输出重定向到 /dev/null 并后台运行，避免日志干扰
          ./subconverter &
          SUB_CONVERTER_PID=$! # 获取后台进程的 PID

          # 等待 subconverter 服务启动完成
          echo "等待 subconverter 服务启动..."
          sleep 15 # 给予足够时间启动

          # URL 编码订阅链接
          ENCODED_META_URL=$(echo "$SUBSCRIPTION_URL_META" | sed 's/\//%2F/g; s/:/%3A/g; s/?/%3F/g; s/&/%26/g; s/=/%3D/g')
          ENCODED_SS_TXT_URL=$(echo "$SUBSCRIPTION_URL_SS_TXT" | sed 's/\//%2F/g; s/:/%3A/g; s/?/%3F/g; s/&/%26/g; s/=/%3D/g')

          # 组合 API URL 参数
          # target=clashr 适用于 Clash Meta (OpenClash)
          # sc=true 开启速度测试 (speed check)
          # fast_url 测速地址
          # tfo=true, udp=true 开启特性
          # rename=true 开启重命名
          # filter=speed%3E0.1 过滤速度，注意URL编码
          
          CONVERSION_API_ENDPOINT="http://localhost:25500/sub?url=${ENCODED_META_URL}|${ENCODED_SS_TXT_URL}&target=clashr&sc=true&fast_url=http%3A%2F%2Fspeed.cloudflare.com%2F__down%3Fbytes%3D10485760&tfo=true&udp=true&rename=true&filter=speed%3E0.1"
          
          echo "从 subconverter API 获取配置: ${CONVERSION_API_ENDPOINT}"

          # 使用 curl 获取配置并保存
          # -sS: 静默模式，但显示错误
          # -L: 遵循重定向
          # -f: 失败时（HTTP 状态码 >= 400）不输出到文件，直接报错
          curl -sSLf -o "${OUTPUT_PATH}" "${CONVERSION_API_ENDPOINT}"
          
          # 停止 subconverter 进程
          echo "停止 subconverter 服务..."
          kill $SUB_CONVERTER_PID

          # 检查文件是否成功生成，如果文件不存在，则工作流失败
          if [ ! -f "$OUTPUT_PATH" ]; then
            echo "错误: subconverter 未能生成文件 ${OUTPUT_PATH}。"
            exit 1
          fi
          echo "Clash 配置已通过 subconverter 生成并保存到 ${OUTPUT_PATH}。"

      # --- 解决非快进问题：在提交前拉取远程最新代码 ---
      - name: 拉取远程最新代码 (解决非快进问题)
        if: success() # 仅当所有前面的步骤都成功时才执行此步骤
        run: |
          echo "尝试拉取远程 main 分支的最新更改..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          if [ $? -ne 0 ]; then # 检查上一个 Git 命令的退出状态码，如果非零则表示失败
            echo "错误: git pull --rebase 失败。可能存在无法自动解决的冲突，请检查仓库历史。"
            exit 1 # 终止工作流并标记为失败
          fi
          echo "远程代码拉取并rebase成功。"

      # --- 提交并推送更新后的配置文件 ---
      - name: 提交并推送更新后的配置文件
        if: success() # 仅当所有前面的步骤都成功时才执行此步骤
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "更新 Clash 配置：从多订阅源获取节点并保存到 sc/clash_config.yaml"
          file_pattern: "${OUTPUT_PATH}" 
          branch: main # 指定目标分支
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: qjlxg <12179157+qjlxg@users.noreply.github.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
