
name: Extract Nodes to YAML

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行
  workflow_dispatch:     # 支持手动触发

jobs:
  extract-nodes:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 安装依赖
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp pyyaml

    # 运行提取脚本
    - name: Run Extract Nodes Script
      run: |
        python extract_nodes_to_yaml.py

    # 检查是否有变更并提交
    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sc/*
        git diff --staged --quiet || git commit -m "Update extracted nodes YAML files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

