name: FlyClash Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  speedtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install FlyClash
        run: go install github.com/FlyClash/FlyClash@latest
      - name: Create output directory
        run: mkdir -p sc
      - name: Run FlyClash test
        run: |
          flyclash \
            --config https://raw.githubusercontent.com/qjlxg/vt/refs/heads/main/clash_config.yaml \
            --concurrent 2 \
            --timeout 10s \
            --output sc/xiecang.yaml || echo "FlyClash failed with exit code $?"
          ls -l sc/
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: speedtest-results
          path: sc/xiecang.yaml
        if: always()
      - name: Commit and Push Results
        run: |
          if [ -f sc/xiecang.yaml ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add sc/xiecang.yaml
            git commit -m "Update speedtest results" || echo "Nothing to commit"
            git push
          else
            echo "No output file generated, skipping commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
