name: Update IPTV List

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0 点运行 (如果你希望更改时间，请调整 cron 表达式)
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Install Python dependencies
      run: |
        pip install requests tqdm # <-- 确保这里包含了 tqdm

    - name: Run IPTV List Updater
      run: python update_iptv_list.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # 添加所有在 sc/ 目录下的更改
        git add sc/
        # 如果你希望提交其他地方的日志文件，也可以添加
        # git add error_log.txt
        git commit -m "Update combined IPTV list [skip ci]" || echo "No changes to commit" # [skip ci] 避免循环触发工作流
        git push origin ${{ github.ref_name }}
      env:
        # GITHUB_TOKEN 是 GitHub Actions 自动提供的，用于授权提交和推送
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
