name: IPTV Processor and Checker

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0 点运行 (日本时间上午 9 点)
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Install dependencies # <-- Add this new step!
      run: |
        pip install pytz requests # Install pytz and ensure requests is also installed

    - name: Run IPTV Processor
      run: python iptv_processor.py
      env:
        # 如果你的脚本需要任何环境变量，可以在这里添加
        # 例如: MY_API_KEY: ${{ secrets.MY_API_KEY }}

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        git commit -m "Update IPTV lists [skip ci]" || echo "No changes to commit"
        git push origin ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
