name: Automated Proxy Management (with SubConv & Mihomo)

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次

jobs:
  process_proxies:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予写入权限，以便推送结果文件

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (for YAML processing)
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Node.js YAML dependencies
        run: npm install js-yaml yq # 安装 yq 工具来更方便地处理 YAML

      - name: Create data directory
        run: mkdir -p data

      - name: Download SubConv v2.1.3 Binary
        run: |
          SUB_CONV_VERSION="v2.1.3"
          # 确保下载链接和文件名正确
          curl -L "https://github.com/SubConv/SubConv/releases/download/${SUB_CONV_VERSION}/subconv-ubuntu-latest-x64.zip" -o subconv.zip
          unzip subconv.zip
          # 解压后，可执行文件通常在解压的根目录或一个子目录内
          # 检查解压内容，通常是 subconv 这个名字
          # 如果解压到子目录 'subconv-ubuntu-latest-x64/'，则需要 mv subconv-ubuntu-latest-x64/subconv .
          # 根据 Release assets 的信息，它解压出来就是 subconv 
          chmod +x subconv # 授予执行权限

      - name: Download Mihomo (Clash Meta) Core for Speed Testing
        # 使用 Mihomo 作为 Clash 核心，它是 Clash Meta 的官方名称
        # 访问 https://github.com/MetaCubeX/mihomo/releases 获取最新版本
        run: |
          MIHOMO_VERSION="v1.18.2" # 请检查 mihomo Release 页面获取最新版本号
          curl -L "https://github.com/MetaCubeX/mihomo/releases/download/${MIHOMO_VERSION}/mihomo-linux-amd64-${MIHOMO_VERSION}.gz" -o mihomo.gz
          gzip -d mihomo.gz
          chmod +x mihomo # 授予执行权限

      - name: Convert and Deduplicate with SubConv
        # 核心步骤：使用 SubConv 转换并去重
        # 根据 SubConv 的用法，-u 参数可以重复提供多个 URL
        # --dedup 启用去重功能
        run: |
          ./subconv convert \
            -u "https://raw.githubusercontent.com/qjlxg/vt/refs/heads/main/clash.yaml" \
            -u "https://raw.githubusercontent.com/qjlxg/my/refs/heads/main/sc/OP404OP.yaml" \
            -o clash \
            --dedup \
            --output converted_clash.yaml

      - name: Perform Speed Test with Mihomo Core
        run: |
          # 从 converted_clash.yaml 提取 proxies 部分，创建测试配置文件
          # Mihomo 的 external-controller 端口与 Clash 兼容
          echo "proxies: $(yq '.proxies' converted_clash.yaml)" > test_config.yaml
          echo "external-controller: 127.0.0.1:9090" >> test_config.yaml
          echo "log-level: info" >> test_config.yaml
          
          # 启动 Mihomo 核心
          ./mihomo -f test_config.yaml &
          MIHOMO_PID=$! # 获取 Mihomo 进程ID
          sleep 5 # 等待 Mihomo 启动

          # 从转换后的文件中获取所有代理名称
          NODE_NAMES=$(yq '.proxies[].name' converted_clash.yaml | tr '\n' ' ')
          echo "Testing nodes: $NODE_NAMES"

          RESULTS_FILE="test_results.txt"
          echo "" > $RESULTS_FILE # 清空文件

          # 逐个测速并记录结果
          for NODE_NAME in $NODE_NAMES; do
            echo "Testing $NODE_NAME..."
            # 请求测速，Mihomo 会返回延迟结果
            LATENCY=$(curl -s -X GET "http://127.0.0.1:9090/proxies/$NODE_NAME/delay?url=https://www.google.com/generate_204&timeout=5000" | jq -r '.delay')
            if [ "$LATENCY" == "null" ] || [ "$LATENCY" == "" ]; then
              LATENCY="Timeout/Error"
            fi
            echo "$NODE_NAME: $LATENCY ms" >> $RESULTS_FILE
          done
          
          kill $MIHOMO_PID # 停止 Mihomo 进程
          sleep 1

      - name: Filter and Organize Proxies Based on Speed Test
        run: |
          node -e '
            const fs = require("fs");
            const yaml = require("js-yaml");

            try {
              const allProxies = yaml.load(fs.readFileSync("converted_clash.yaml", "utf8")).proxies;
              const testResults = fs.readFileSync("test_results.txt", "utf8").split("\n").filter(line => line.trim() !== "");

              const proxyLatencyMap = new Map();
              testResults.forEach(line => {
                const parts = line.split(": ");
                if (parts.length === 2) {
                  const name = parts[0];
                  let latency = parseInt(parts[1]);
                  if (isNaN(latency) || latency === 0) { // 处理超时或错误
                    latency = Infinity; // 设置为无限大，以便排序时排在后面
                  }
                  proxyLatencyMap.set(name, latency);
                }
              });

              // 过滤掉不可用或延迟过高的节点，并按延迟排序
              const sortedAndFilteredProxies = allProxies
                .filter(p => p && p.name && proxyLatencyMap.has(p.name) && proxyLatencyMap.get(p.name) < Infinity) // 移除超时节点
                .sort((a, b) => proxyLatencyMap.get(a.name) - proxyLatencyMap.get(b.name)); // 按延迟升序

              // 构建最终的 Clash 配置，包含基本信息和代理组
              const finalConfig = {
                "port": 7890,
                "socks-port": 7891,
                "allow-lan": false,
                "mode": "rule",
                "log-level": "info",
                "external-controller": "0.0.0.0:9090",
                "proxies": sortedAndFilteredProxies,
                "proxy-groups": [
                    {
                        "name": "Proxy",
                        "type": "select",
                        "proxies": sortedAndFilteredProxies.map(p => p.name) // 将所有可用节点加入选择组
                    },
                    {
                        "name": "Direct",
                        "type": "direct"
                    }
                ],
                "rules": [
                    "MATCH,Proxy"
                ]
              };

              fs.writeFileSync("data/clash.yaml", yaml.dump(finalConfig, { indent: 2 }));
              console.log("Proxies collected, converted, tested, and saved successfully!");

            } catch (e) {
              console.error("Error processing proxies:", e);
              process.exit(1);
            }
          '

      - name: Commit and push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add data/clash.yaml
          git commit -m "Update Clash config with tested proxies" || echo "No changes to commit"
          git push
