name: LiteSpeedTest & Update Clash Config

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v4
        with:
          path: .

      - name: Download Full Clash Configuration
        run: |
          CONFIG_URL="https://raw.githubusercontent.com/qjlxg/vt/refs/heads/main/clash_config.yaml"
          curl -S -L --retry 5 --retry-delay 5 --connect-timeout 10 --max-time 60 --output clash_config.yaml "$CONFIG_URL" || { echo "Config download failed"; exit 1; }
          ls -l clash_config.yaml
          if ! grep -q "proxies:" clash_config.yaml; then
            echo "Invalid Clash configuration file"
            exit 1
          fi

      - name: Create LiteSpeedTest Config
        run: |
          echo '{"test_download": true, "test_upload": false, "ping_count": 3}' > config.json
          ls -l config.json

      - name: Clone LiteSpeedTest Repository
        uses: actions/checkout@v4
        with:
          repository: xxf098/LiteSpeedTest
          path: LiteSpeedTest
          # ref: v0.10.0 # 移除或替换为最新版本

      - name: Debug Directory Structure
        run: |
          pwd
          ls -la
          ls -la LiteSpeedTest || echo "LiteSpeedTest directory not found"
          ls -la LiteSpeedTest/docker || echo "docker directory not found"
          ls -la LiteSpeedTest/docker/Dockerfile || echo "Dockerfile not found"

      - name: Patch LiteSpeedTest Dockerfile
        run: |
          DOCKERFILE_PATH="./LiteSpeedTest/docker/Dockerfile"
          if [ ! -f "$DOCKERFILE_PATH" ]; then
            echo "Dockerfile not found at $DOCKERFILE_PATH"
            exit 1
          fi
          if ! grep -q "GOOS=js GOARCH=wasm" "$DOCKERFILE_PATH"; then
            echo "Dockerfile does not contain expected go get command, skipping patch"
          else
            sed -i '/RUN GOOS=js GOARCH=wasm go get -u .\/.../i \
              RUN go mod tidy\nRUN go mod download' "$DOCKERFILE_PATH"
            sed -i '/^RUN GOOS=js GOARCH=wasm go get -u .\/.../d' "$DOCKERFILE_PATH"
            cat "$DOCKERFILE_PATH"
          fi

      - name: Build LiteSpeedTest Docker Image
        run: |
          docker build --network=host -t litespeedtest-custom -f ./LiteSpeedTest/docker/Dockerfile ./LiteSpeedTest
          docker images | grep litespeedtest-custom

      - name: Run LiteSpeedTest
        shell: bash
        run: |
          pwd
          ls -la
          mkdir -p sc || { echo "Failed to create sc directory"; exit 1; }
          ls -ld sc
          docker run --rm --network host \
            -v "$(pwd)/clash_config.yaml:/app/clash_config.yaml" \
            -v "$(pwd)/config.json:/app/config.json" \
            -v "$(pwd)/sc:/app/sc" \
            litespeedtest-custom \
            /usr/local/bin/lite \
            --test file:///app/clash_config.yaml \
            --config /app/config.json \
            --output-mode 4 \
            --output-path /app/sc/xxf098.txt
          chmod -R 777 sc
          if [ ! -s sc/xxf098.txt ]; then
            echo "Error: LiteSpeedTest output file is empty or not created."
            exit 1
          fi
          cat sc/xxf098.txt

      - name: Commit and Push Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add sc/xxf098.txt
          git commit -m "Update Clash config with LiteSpeedTest results" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
